Credit Card Feature
MattHamburger/business_banking pull request #41
Opened 2021-05-03 13:07 UTC by christian-huntington

Refactoring:
- Many classes/methods were refactored according the design patterns discussed at last meeting.

Implementation of external Plugin (PDF / Printing):
- Included 2 external libs on the pubspec.yaml (pdf and printing)
- Those libs are used to generate a Payment Confirmation PDF file and to allow the user to print/share that file.

Mockoon JSON file:
- Included Credit Card paths and json responses. 

Unit tests:
- More tests were implemented.

2021-05-03 13:13 UTC, aelshamy commented
@christian-huntington can you fix the conflicts

2021-05-03 13:47 UTC, christian-huntington commented
@aelshamy I have resolve the conflicts related to credit_card feature, but I removed any changes to the mockoon json file. Plz merge these changes and I'll work on that file soon.

2021-05-03 14:00 UTC, aelshamy requested changes

2021-05-03 14:00 UTC, aelshamy commented on business_banking/test/features/credit_card/ui/payment_request/credit_card_payemnt_request_screen_test.dart
> +    expect(find.byType(CreditCardPaymentRequestScreen), findsOneWidget);
if you are testing the screen, you need to verify the elements on the screen themselves

2021-05-03 14:00 UTC, aelshamy commented on business_banking/test/features/credit_card/ui/payment_request/credit_card_payemnt_request_screen_test.dart
> +  testWidgets('CreditCardScreen viewModel values x screen values',
also remove the comments

2021-05-03 16:09 UTC, christian-huntington commented on business_banking/test/features/credit_card/bloc/credit_card_bloc_test.dart
> +    verify(creditCardPaymentRequestUseCaseMock.updatePaymentValue(any)).called(1);
OK! Got it! I've changed it to: 

verify(creditCardPaymentRequestUseCaseMock.updatePaymentValue(event.paymentValue)).called(1);

2021-05-03 16:12 UTC, christian-huntington commented on business_banking/lib/features/credit_card/bloc/credit_card_bloc.dart
> +abstract class CreditCardViewEvents extends Equatable {}
OK! Moved to a new file called "bloc/credit_card_view_events.dart".

2021-05-03 16:14 UTC, christian-huntington commented on business_banking/test/features/credit_card/bloc/credit_card_bloc_test.dart
> +    verify(creditCardPaymentRequestUseCaseMock.validatePaymentInformation(any)).called(1);
OK!

2021-05-03 16:17 UTC, christian-huntington commented on business_banking/test/features/credit_card/ui/credit_card/credit_card_actions_test.dart
> +void main() {
I'm having problems when testing "navigation". I'm going to remove this file and check with you later how to test CFRouterScope navigation.

2021-05-03 16:25 UTC, christian-huntington commented on business_banking/test/features/credit_card/ui/payment_request/credit_card_payemnt_request_screen_test.dart
> +    expect(find.byType(CreditCardPaymentRequestScreen), findsOneWidget);
OK! I've added the tests to check the screen elements and event actions.

2021-05-04 12:59 UTC, aelshamy approved these changes

2021-05-04 13:00 UTC, aelshamy commented on business_banking/lib/features/credit_card/bloc/credit_card_bloc.dart
> +import 'package:pdf/widgets.dart' as pw;
I thought you update that, right?

2021-05-04 13:01 UTC, aelshamy commented on business_banking/lib/features/credit_card/bloc/credit_card_bloc.dart
> +  Future<pw.Document> generatePDFPaymentConfirmation(CreditCardPaymentResponseViewModel viewModel) async {
did you push this update, I saw yesterday that you moved to the usecase, but it is not showing here

2021-05-04 13:01 UTC, aelshamy requested changes
please check the last two comments

2021-05-06 00:27 UTC, merged